### ISSUE TITLE
Chart about performance

### ISSUE THREAD

**Issue by mrkev** [ratel-rust/ratel-core#135]
Hello! I recently came across the project; cool stuff! I am curious about this chart on the README:

![46786973-beee0c80-cd36-11e8-989a-62b92d624d38](https://user-images.githubusercontent.com/1285131/68100577-9d9a1a00-fe7d-11e9-9b39-c93b88e9f842.png)

This is awesome— but how was it measured? I would love to read a blog post about it if there is one. I'm also curious to know what versions of which parses were used. Perhaps it'd be good to have something explaining how the chart was constructed linked from the README. (: Thanks!

**Comment by cmtt** [comment]
Hello @mrkev, thank you for opening the issue.

Adding more information about our benchmark to `README.md` is a good idea. I will also update all dependencies in order to keep the benchmark up to date. The actual graphics has been created using the observations by @maciejhirsz.

For the time being, you'll be able to reproduce the benchmark by running the `npm run benches` command in the `ffi` folder - ensure that all Node.js dependencies have been installed in advance.

**Comment by mrkev** [comment]
Ah sweet, thanks for the heads up!
