### ISSUE TITLE
what's the status of this project?

### ISSUE THREAD

**Issue by piaoger** [ratel-rust/ratel-core#63]
ratel is a cool project. It seems that the rewrite branch is still quite active. 
Do you have any roadmap or plan to integrate back to master branch?

**Comment by maciejhirsz** [comment]
Hey @piaoger. I'm hoping to merge rewrite back to master sooner rather than later. It's not as feature complete as the old master, but it's shaping itself to be light years of master.

- It's much faster (by a factor of 3 or s) thanks to switching from vecs and boxes to an arena allocator.
- All AST nodes have location data.
- There is a visitor pattern implementation along with some basic scope analysis (so that transforming `const` / `let` with name conflicts should work just as it does in Babel / TS).

There is also a WASM build that isn't on the repo yet. You can preview it parsing to ast here: http://maciej.codes/ratel-wasm/

**Comment by piaoger** [comment]
Thanks for your response. The WASM preview demo is great .
Looking forward to the merging back ...

**Comment by cmtt** [comment]
The code of the WASM preview will be added to the project soon as well.
